### ISSUE TITLE
cannot open <cnn_model.net> from apk

### ISSUE THREAD

**Issue by thelinuxmaniac** [soumith/torch-android#19] opened 2016-02-04 09:14 UTC
Hi,
I am trying to load a CNN model -- saved using torch.save() -- in a lua script in Android environment as follows:

```
android=1
require 'torch'
require 'nnx'
require 'dok'
require 'image'

torch.setdefaulttensortype('torch.DoubleTensor')

model = torch.load('cnn_model.net','r','apk'):double()
...
```

I get the following error in Android logcat:

```
I/torchdemo    (31607): Torch Error doing resource
I/torchdemo    (31607): cannot open <cnn_model.net> from apk
```

Am I missing something here? Should I do something before I can load models saved using torch.save()?

**Comment by thelinuxmaniac** [comment] 2016-02-04 11:01
I missed to describe my app's directory tree structure, which is as follows:

```
app/assets/cnn_model.net
app/jni/
app/libs/
app/obj/
app/res/
app/src/
app/AndroidManifest.xml
...
```

**Comment by thelinuxmaniac** [comment] 2016-02-04 12:36
I see the following comment in file [https://github.com/soumith/torch-android/blob/master/src/lib/TH/THApkFile.h]:

```
// must be set by someone on the android side
// AAssetManager * but kept void* to avoid dependency issues
void THApkFile_setAAssetManager(void *am);
```

So, it appears that I have to manually set the `*THApkFile_AAssetManager` variable using the `THApkFile_setAAssetManager()` function. So, in my `*_initTorch()` code, I do the following:

```
    // get native asset manager. This allows access to files stored in the assets folder
    AAssetManager* manager = AAssetManager_fromJava(env, assetManager);
    assert( NULL != manager);

    THApkFile_setAAssetManager(manager);

    lua_State *L = NULL;
    L = inittorch(manager); // create a lua_State
    ....
```

But now, I get the following error (via logcat):

```
[string "torch/File"]:235: table index is nil
```

I am still trying to find out what this error means.

**Comment by thelinuxmaniac** [comment] 2016-02-04 12:51
Interestingly, when I load the [face.net.arm](https://github.com/soumith/torch-android/blob/master/facedetector_e-lab/assets/face.net.arm) file, I get the following error:

```
[string "torch/File"]:240: unknown object
```

and, when I load my own model file (cnn_model.net), I get the following error:

```
[string "torch/File"]:235: table index is nil
```

So, it seems that I need to first load some library (@todo) in order to read the objects saved in the model file.

**Comment by mseyed** [comment] 2016-02-10 05:00
There are two other issues on this thread with the same problem. In all of them the problem is loading a pre trained model in android. Anyone knows the solution? Has anyone successfully loaded a trained model in android?

https://github.com/soumith/torch-android/issues/15
https://github.com/soumith/torch-android/issues/13

**Comment by boerjames** [comment] 2016-02-10 21:50
Have you tried the refactor branch?

**Comment by yonadavs** [comment] 2016-02-11 08:09
If you're having trouble loading it as described in the demos, then don't put the pre-trained NN in the project's 'assets' directory, just ump it on the device storage, and open it like this:
`model = torch.load('/sdcard/torch/pretrained.txt', 'ascii', 'r')`
(works the same with a binary net, just cahnge the 2nd param.)

**Comment by soumith** [comment] 2016-02-15 04:16
I just did a huge refactor and merged it to master.
Now you can do something like:
model = torch.load('cnn_model.net', 'apkbinary64') (apkbinary64 because you saved the model on a 64-bit computer).

Example is here: https://github.com/soumith/torch-android/blob/master/demos/android-demo-cifar/application/assets/init-only.lua#L49
in this case, they are using apkbinary32 because they trained and saved the model on 32-bit computer.

**Closed as completed by soumith** 2016-02-15 04:16 UTC

**Comment by thelinuxmaniac** [comment] 2016-02-16 09:21
Now I face problems compiling torch-android on 64bit Ubuntu 14.04:

```
$ ./build.sh
Android NDK found at: /home/duttaa/Android/ndk/android-ndk-r10d/
==== Building LuaJIT 2.1.0-beta1 ====
make -C src
make[1]: Entering directory `/home/duttaa/mybin/torch7/torch-android/torch-android/distro/exe/luajit-rocks/luajit-2.1/src'
HOSTLINK  host/minilua
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
collect2: error: ld returned 1 exit status
make[1]: *** [host/minilua] Error 1
...........
```

I think I have to create symbolic links to the compatible gcc shared libraries, but I am not sure which one?

**Comment by thelinuxmaniac** [comment] 2016-02-16 09:23
Since I have a 64bit Ubuntu 14.04, do I really need to install these 32 bit libraries (as instructed in the README.md) `sudo apt-get install libx32gcc-4.8-dev libc6-dev-i386` ?

**Comment by thelinuxmaniac** [comment] 2016-02-16 09:50
Since I have gcc-4.9 installed as well, I had to do `sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50` to force the build script to use the gcc-4.8 version. Now, the compilation works:

```
==== Building LuaJIT 2.1.0-beta1 ====
make -C src
..........
LINK      luajit
OK        Successfully built LuaJIT
make[1]: Leaving directory `/home/duttaa/mybin/torch7/torch-android/distro/exe/luajit-rocks/luajit-2.1/src'
==== Successfully built LuaJIT 2.1.0-beta1 ====
```

**Comment by thelinuxmaniac** [comment] 2016-02-16 10:28
I can now load my models. Thank you @soumith and others for help.
